# Generated by Django 4.0.6 on 2023-09-13 12:24

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStructures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
            ],
        ),
        migrations.CreateModel(
            name='DSAsSheetsLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('by', models.CharField(default=None, max_length=100, null=True)),
                ('reference', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plateforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('color', models.CharField(default=None, max_length=25, null=True)),
                ('bgcolor', models.CharField(default=None, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('filename', models.CharField(default=None, max_length=150, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('plateforms', models.IntegerField(default=0, null=True)),
                ('links', models.IntegerField(default=0, null=True)),
                ('datastructures', models.IntegerField(default=0, null=True)),
                ('dsasheetlist', models.IntegerField(default=0, null=True)),
                ('subproblem', models.IntegerField(default=0, null=True)),
                ('detailsset', models.CharField(default=None, max_length=500, null=True)),
                ('timecomplexity', models.CharField(default=None, max_length=35, null=True)),
                ('auxiliaryspace', models.CharField(default=None, max_length=35, null=True)),
                ('SolutionsCount', models.IntegerField(default=0, null=True)),
                ('SolutionsContinueCount', models.IntegerField(default=0, null=True)),
                ('JoiningDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('extension', models.CharField(default=None, max_length=10, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default=None, max_length=150, null=True)),
                ('plateforms', models.IntegerField(default=0, null=True)),
                ('programminglanguages', models.IntegerField(default=0, null=True)),
                ('datastructures', models.IntegerField(default=0, null=True)),
                ('attachments', models.IntegerField(default=0, null=True)),
                ('codesubmissions', models.CharField(default=None, max_length=1000, null=True)),
                ('timecomplexity', models.CharField(default=None, max_length=35, null=True)),
                ('auxiliaryspace', models.CharField(default=None, max_length=35, null=True)),
                ('explainlevel', models.IntegerField(default=1, null=True)),
                ('JoiningDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateTimeField(auto_now=True)),
                ('problem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.problems')),
            ],
        ),
        migrations.CreateModel(
            name='SubProblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('problem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.problems')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionsAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showntitle', models.CharField(default=None, max_length=200, null=True)),
                ('link', models.CharField(default=None, max_length=200, null=True)),
                ('note', models.CharField(default=None, max_length=1000, null=True)),
                ('problem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.problems')),
            ],
        ),
        migrations.CreateModel(
            name='solutions_datastructures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datastructure_id', models.IntegerField(default=None, null=True)),
                ('solution_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.solutions')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionAndSolutionsAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.problems')),
                ('solution_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.solutions')),
                ('solutionattachments_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.solutionsattachments')),
            ],
        ),
        migrations.CreateModel(
            name='problems_plateforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateform_id', models.IntegerField(default=None, null=True)),
                ('problem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.problems')),
            ],
        ),
        migrations.CreateModel(
            name='problems_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default=None, max_length=120, null=True)),
                ('text', models.CharField(default=None, max_length=25, null=True)),
                ('plateform_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.plateforms')),
                ('problem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.problems')),
            ],
        ),
        migrations.CreateModel(
            name='problems_dsasheetlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsasheetlist_id', models.IntegerField(default=None, null=True)),
                ('problem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.problems')),
            ],
        ),
        migrations.CreateModel(
            name='problems_datastructures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datastructure_id', models.IntegerField(default=None, null=True)),
                ('problem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.problems')),
            ],
        ),
    ]
