# Generated by Django 4.0.6 on 2023-08-27 16:55

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCodeCollections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('filename', models.CharField(default=None, max_length=150, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('plateforms', models.IntegerField(default=0, null=True)),
                ('links', models.IntegerField(default=0, null=True)),
                ('datastructures', models.IntegerField(default=0, null=True)),
                ('dsasheetlist', models.IntegerField(default=0, null=True)),
                ('subproblem', models.IntegerField(default=0, null=True)),
                ('detailsset', models.CharField(default=None, max_length=500, null=True)),
                ('timecomplexity', models.CharField(default=None, max_length=35, null=True)),
                ('auxiliaryspace', models.CharField(default=None, max_length=35, null=True)),
                ('SolutionsCount', models.IntegerField(default=0, null=True)),
                ('SolutionsContinueCount', models.IntegerField(default=0, null=True)),
                ('JoiningDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubProblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('problem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.problems')),
            ],
        ),
        migrations.CreateModel(
            name='problems_plateforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateform_id', models.IntegerField(default=None, null=True)),
                ('problem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.problems')),
            ],
        ),
        migrations.CreateModel(
            name='problems_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default=None, max_length=120, null=True)),
                ('text', models.CharField(default=None, max_length=25, null=True)),
                ('plateform_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.plateforms')),
                ('problem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.problems')),
            ],
        ),
        migrations.CreateModel(
            name='problems_dsasheetlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsasheetlist_id', models.IntegerField(default=None, null=True)),
                ('problem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.problems')),
            ],
        ),
        migrations.CreateModel(
            name='problems_datastructures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datastructure_id', models.IntegerField(default=None, null=True)),
                ('problem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.problems')),
            ],
        ),
    ]
