# Generated by Django 4.0.6 on 2023-07-17 18:37

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCodeCollections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('plateforms', models.IntegerField(default=0, null=True)),
                ('datastructures', models.IntegerField(default=0, null=True)),
                ('detailsset', models.CharField(default=None, max_length=500, null=True)),
                ('timecomplexity', models.CharField(default=None, max_length=35, null=True)),
                ('auxiliaryspace', models.CharField(default=None, max_length=35, null=True)),
                ('JoiningDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateforms', models.IntegerField(default=0, null=True)),
                ('programminglanguages', models.IntegerField(default=0, null=True)),
                ('datastructures', models.IntegerField(default=0, null=True)),
                ('codesubmissions', models.CharField(default=None, max_length=1000, null=True)),
                ('timecomplexity', models.CharField(default=None, max_length=35, null=True)),
                ('auxiliaryspace', models.CharField(default=None, max_length=35, null=True)),
                ('explainlevel', models.IntegerField(default=1, null=True)),
                ('JoiningDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateTimeField(auto_now=True)),
                ('problem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.problems')),
            ],
        ),
        migrations.CreateModel(
            name='solutions_datastructures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datastructure_id', models.IntegerField(default=None, null=True)),
                ('solution_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.solutions')),
            ],
        ),
        migrations.CreateModel(
            name='problems_plateforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateform_id', models.IntegerField(default=None, null=True)),
                ('problem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.problems')),
            ],
        ),
        migrations.CreateModel(
            name='problems_datastructures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datastructure_id', models.IntegerField(default=None, null=True)),
                ('problem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.problems')),
            ],
        ),
    ]
