# Generated by Django 4.0.6 on 2023-08-27 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCodeCollections', '0002_problems_subproblems_problems_plateforms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default=None, max_length=150, null=True)),
                ('plateforms', models.IntegerField(default=0, null=True)),
                ('programminglanguages', models.IntegerField(default=0, null=True)),
                ('datastructures', models.IntegerField(default=0, null=True)),
                ('attachments', models.IntegerField(default=0, null=True)),
                ('codesubmissions', models.CharField(default=None, max_length=1000, null=True)),
                ('timecomplexity', models.CharField(default=None, max_length=35, null=True)),
                ('auxiliaryspace', models.CharField(default=None, max_length=35, null=True)),
                ('explainlevel', models.IntegerField(default=1, null=True)),
                ('JoiningDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateTimeField(auto_now=True)),
                ('problem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.problems')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionsAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showntitle', models.CharField(default=None, max_length=200, null=True)),
                ('link', models.CharField(default=None, max_length=200, null=True)),
                ('note', models.CharField(default=None, max_length=1000, null=True)),
                ('problem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.problems')),
            ],
        ),
        migrations.CreateModel(
            name='solutions_datastructures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datastructure_id', models.IntegerField(default=None, null=True)),
                ('solution_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.solutions')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionAndSolutionsAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.problems')),
                ('solution_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.solutions')),
                ('solutionattachments_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.solutionsattachments')),
            ],
        ),
    ]
