# Generated by Django 4.0.6 on 2023-08-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCodeCollections', '0002_problems_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='links',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
