# Generated by Django 4.0.6 on 2023-07-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCodeCollections', '0002_problems_solutions_solutions_datastructures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastructures',
            name='extension',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
