# Generated by Django 4.0.6 on 2023-08-22 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCodeCollections', '0003_problems_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionsattachments',
            name='solution_id',
        ),
        migrations.AddField(
            model_name='solutionsattachments',
            name='problem_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.problems'),
        ),
        migrations.CreateModel(
            name='SolutionsAndProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.problems')),
                ('solution_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.solutions')),
                ('solutionattachments_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.solutionsattachments')),
            ],
        ),
    ]
