# Generated by Django 4.0.6 on 2023-08-22 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCodeCollections', '0004_remove_solutionsattachments_solution_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolutionsAndProblem',
            new_name='SolutionAndSolutionsAttachments',
        ),
    ]
