# Generated by Django 4.0.6 on 2023-07-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCodeCollections', '0004_remove_datastructures_extension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='filename',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='solutions',
            name='filename',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
