# Generated by Django 4.0.6 on 2023-08-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCodeCollections', '0005_problems_filename_solutions_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='SolutionsCount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
