# Generated by Django 4.0.6 on 2023-08-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCodeCollections', '0007_dsassheetslists_problems_dsasheetlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsassheetslists',
            name='by',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
