# Generated by Django 4.0.6 on 2023-08-03 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCodeCollections', '0009_subproblems'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionsAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default=None, max_length=200, null=True)),
                ('note', models.CharField(default=None, max_length=200, null=True)),
                ('solution_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCodeCollections.solutions')),
            ],
        ),
    ]
