# Generated by Django 4.0.6 on 2023-08-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCodeCollections', '0010_solutionsattachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='subproblem',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
