# Generated by Django 4.0.6 on 2023-08-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCodeCollections', '0012_solutions_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionsattachments',
            name='showntitle',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
