# Generated by Django 4.0.6 on 2023-08-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCodeCollections', '0013_solutionsattachments_showntitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='SolutionsContinueCount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
