# Generated by Django 4.0.6 on 2023-08-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCodeCollections', '0014_problems_solutionscontinuecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='SolutionsContinueCount',
        ),
        migrations.RemoveField(
            model_name='problems',
            name='SolutionsCount',
        ),
    ]
