# Generated by Django 4.0.6 on 2023-08-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCodeCollections', '0015_remove_problems_solutionscontinuecount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='SolutionsContinueCount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='SolutionsCount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
